url: "https://en-partance.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "En Partance"
description: "En partance is a site for departing, in spite of not knowing where the destination is."


default_locale: ja

twitter_username: "mkataoka73"
